### ISSUE TITLE
Buttons Hiding for Future Enhancement

### ISSUE THREAD

**Issue by vippium** [01101sam/Comfortable-Youtube#1]
If you are going to add a feature for hiding buttons, pls try to add support for these buttons like Subscribe, Clip, Three-Dot menu, etc. There is a script available on Tampermonkey which can hide these buttons but the script is not updated since last year, so that script is not working well.

It will be great if you add this because I don't like these buttons.

And pls add support for RYD in your script bro...So that, we don't need to install that script or extension separately.
Thanks

**Comment by 01101sam** [comment]
Good Idea, I also have thought about that already

**Comment by 01101sam** [comment]
I'm trying to add a settings UI inside, so the update will be delayed.
My plan is add the UI to control most of the hide / unhide feature and etc.
That's why I'm getting delayed, thanks for you understanding.

**Comment by Vipin2003** [comment]
It's ok bro... We're not in hurrry for update.

**Comment by Vipin2003** [comment]
In nxt update, try to remove these banner ads. They sometimes appears on the top.

![2023-07-07_19h35_32](https://github.com/01101sam/Comfortable-Youtube/assets/93650504/d28747b6-7bd7-43fa-a42b-4cdced3320d4)

**Comment by 01101sam** [comment]
> how's that if you push beta or pre-release of your UI with conditions and disclaimer. So that, it will be more easy to find out bugs. And, pushing every beta with more improvement and bug fixes.
> 
> I think that it would be nice.
> 
> Bcoz finding bugs by own is more difficult than getting them from public.

Yes I think this is nice too if I have enough time to do it so, sorry.
