### ISSUE TITLE
Home Ads are back...Script needs an update

### ISSUE THREAD

**Issue by 01101sam** [01101sam/Comfortable-Youtube#4]
### Discussed in https://github.com/01101sam/Comfortable-Youtube/discussions/3

<div type='discussions-op-text'>

<sup>Originally posted by **Vipin2003** August 15, 2023</sup>
Home ads are back again. Script is no more blocking Home ads. Can you pls update the script. Thanks.</div>

**Comment by 01101sam** [comment]
Home page ad were removed by `Removed home page banner promotion.`
Doesn't seem to have any problem.
If you encountered that ad again, please export your XHR (highlighted) and send it here.
![image](https://github.com/01101sam/Comfortable-Youtube/assets/100821827/abfd25e8-d5e4-4b3b-94a0-c33d673eee23)

## Important: Make sure you didn't logged in before exporting, or do logout after exported the XHR
**It contains sensitive data**

**Comment by Vipin2003** [comment]
Currently, it is resolved after reinstalling chrome....will share if happens again

**Comment by Vipin2003** [comment]
[www.youtube.com.zip](https://github.com/01101sam/Comfortable-Youtube/files/12421756/www.youtube.com.zip)

I encountered this issue again after updating chrome. I also use some other scripts with ur's too from long time but I get this issue again today. I've compressed the file to zip as github won't support HAR files.

**Comment by 01101sam** [comment]
> [www.youtube.com.zip](https://example.com)
> 
> I encountered this issue again after updating chrome. I also use some other scripts with ur's too from long time but I get this issue again today. I've compressed the file to zip as github won't support HAR files.

Thanks for letting me know and provided HAR file, for you safety I've downloaded the file and removed the link.
I'll check that request flow tomorrow.

**Comment by 01101sam** [comment]
> [www.youtube.com.zip](https://example.com)
> 
> I encountered this issue again after updating chrome. I also use some other scripts with ur's too from long time but I get this issue again today. I've compressed the file to zip as github won't support HAR files.

Upon checking the file you provided, I can't import it.
After open and checked at the end, it seems the file was corrupted.
I'm sorry but I can't continue to investigate the problem.

**Comment by Vipin2003** [comment]
Check this one, if it works.

[HAR File]("C:\Program Files\Google\Chrome\Application\chrome.exe")

**Comment by Vipin2003** [comment]
It happened today also...Check this latest.
[www.youtube.com.zip](https://github.com/01101sam/Comfortable-Youtube/files/15113153/www.youtube.com.zip)

**Comment by 01101sam** [comment]
> It happened today also...Check this latest.
> 
> 

Got it. I'll check it tomorrow. Thx

**Comment by 01101sam** [comment]
@Vipin2003 upon checking your HAR file, I can't find any of the keywords: `playerAds`, `adPlacements`, `adSlotRenderer`, `bannerPromoRenderer`.
Please make sure you did get the banner.

Please let me know if I missed something.

**Comment by Vipin2003** [comment]
> @Vipin2003 upon checking your HAR file, I can't find any of the keywords: `playerAds`, `adPlacements`, `adSlotRenderer`, `bannerPromoRenderer`. Please make sure you did get the banner.
> 
> Please let me know if I missed something.

It is showing in Player...not anywhere else. Bcox of Google's new restrictions on ads. I tried the script even with reinstalling chrome, even on Firefox too. But it is showing ads in Player only. Check for ance again, or try to update the script.

**Comment by 01101sam** [comment]
@Vipin2003 I've updated the script since I accidentally switched to a non-premium account and saw the banner.
If you got any other promotion banner / header, please tell me followed by a HAR file :)

**Comment by Vipin2003** [comment]
> @Vipin2003 I've updated the script since I accidentally switched to a non-premium account and saw the banner. If you got any other promotion banner / header, please tell me followed by a HAR file :)

If I found any...I'll surely do that.
